# spring
spring:
  # 环境配置
  profiles:
    active: test
  # session
  session:
    timeout: 604800
  # datasource
  datasource:
    # mysql
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/yunpin?characterEncoding=utf-8&useSSL=false&allowMultiQueries=true
    # druid
    type: com.alibaba.druid.pool.DruidDataSource
    name: yunpin-dataSource
    druid:
      # 连接池初始大小 最小 最大
      initialSize: 1
      minIdle: 1
      maxActive: 3
      # 连接等待超时
      maxWait: 60000
      # 检测空闲连接的时间间隔
      timeBetweenEvictionRunsMillis: 60000
      # 连接在池中最小生存的时间
      minEvictableIdleTimeMillis: 300000
      # 检测连接为有效 sql
      validationQuery: select 'x'
      # 关闭监控
      web-stat-filter:
        enabled: false
      stat-view-servlet:
        enabled: false
  # redis
  redis:
    host: localhost
    port: 6379
    database: 0
    # 超时(毫秒)
    timeout: 10000
    # 连接池配置
    lettuce:
      pool:
        # 最大连接数
        max-active: 8
        # 最大阻塞等待时间,-1为无限制
        max-wait: -1
        # 最大空闲连接数
        max-idle: 8
        # 最小空闲连接数
        min-idle: 0
  # 模板配置
  thymeleaf:
    # 避免模板更改导致重启
    cache: false
    # 标签bug
    mode: HTML
    # 前缀
    prefix: classpath:/static/
    # 后缀
    suffix: .html


# mybatis
mybatis:
  type-aliases-package: com.hlx.cloudevaluation.model
  mapperLocations: classpath:mapper/*.xml
  configuration:
    mapUnderscoreToCamelCase: true